### ISSUE TITLE
Error: setState() called after dispose():

### ISSUE THREAD

**Issue by dheerajsarwaiya** [jonatadashi/youtube_plyr_iframe#13]
How to resolve the following error in web? It came in the original youtube_iplayer_frame package too.

this comes only appear in web version

`
    at platform_view$._PlatformViewLinkState.new.[_onPlatformViewCreated] (http://localhost:38095/packages/flutter/src/widgets/platform_view.dart.lib.js:1261:12)
    at http://localhost:38095/packages/flutter/src/widgets/platform_view.dart.lib.js:624:12
    at _RootZone.runUnary (http://localhost:38095/dart_sdk.js:38889:58)
    at _FutureListener.then.handleValue (http://localhost:38095/dart_sdk.js:33875:29)
    at handleValueCallback (http://localhost:38095/dart_sdk.js:34435:49)
    at Function._propagateToListeners (http://localhost:38095/dart_sdk.js:34473:17)
    at _Future.new.[_completeWithValue] (http://localhost:38095/dart_sdk.js:34315:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:38095/dart_sdk.js:34338:35)
    at Object._microtaskLoop (http://localhost:38095/dart_sdk.js:39176:13)
    at _startMicrotaskLoop (http://localhost:38095/dart_sdk.js:39182:13)
    at http://localhost:38095/dart_sdk.js:34689:9

`
here is the flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Connected device (1 available)

**Comment by jonatadashi** [comment]
Just remove `_controller.close();`
