### ISSUE TITLE
Error: Bad state: Cannot add new events after calling close

### ISSUE THREAD

**Issue by dannycortesv** [jonatadashi/youtube_plyr_iframe#20]
Seems that .listen is still adding new data after .close? I need to dispose and re-creates the youtubeplayer any way to avoid this error?

Error: Bad state: Cannot add new events after calling close
    at Object.throw_ [as throw] (http://localhost:64685/dart_sdk.js:5334:11)
    at _AsyncBroadcastStreamController.new.add (http://localhost:64685/dart_sdk.js:32891:55)
    at controller.YoutubePlayerController.new.add (http://localhost:64685/packages/youtube_plyr_iframe/src/helpers/youtube_value_builder.dart.lib.js:960:32)
    at http://localhost:64685/packages/youtube_plyr_iframe/src/helpers/youtube_value_builder.dart.lib.js:562:45
    at Object._checkAndCall (http://localhost:64685/dart_sdk.js:5544:16)
    at Object.dcall (http://localhost:64685/dart_sdk.js:5549:17)
    at http://localhost:64685/dart_sdk.js:105416:21

**Comment by jonatadashi** [comment]
Sorry for the late response, this should be fixed with  `youtube_plyr_iframe: ^2.0.5+1`
